version: '3.5'
services: 
  db-server:
    image: postgres:alpine
    volumes:
      - ./DB/data:/var/lib/postgresql/data:rw
    env_file: 
      - ./DB/env_file
    networks:
      main_net:
        aliases: 
         - db-server

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    depends_on:
      - db-server
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    restart: unless-stopped

    networks:
      main_net:
        aliases: 
          - pgadmin-server

  dashboard:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./Grafana/data:/var/lib/grafana:rw
    
    networks:
      main_net:
        aliases:
         - grafana

networks:
  main_net:
    driver: bridge
    driver_opts: 
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24

